- README.org
Nothing exceptional here, another `straight.el` user should probably check this out but this is more or less what I have in my running configuration. I simply added the installation instructions using pure `straight.el` and `straight.el` alongside `use-package`
> Update README to include straight.el instructions

- org-noter-core.el
- org-noter.el
I was finding that in a fresh emacs session, `org-noter-start-from-dired` was not loaded, so nothing would happen.  Turns out that as a startup commnad, it needs to be autoloaded.
I moved it from `org-noter-core.el` to `org-noter.el` and gave it the `;;;###autoload` magic command.
Tested on my local MELPA instance and seems to work fine.
> autoload org-noter-start-from-dired from org-noter.el

- modules/org-noter-djvu.el
- modules/org-noter-nov.el
- modules/org-noter-pdf.el
This fixes #9.
Original code was targeting package.el; it doesn't work at all for `straight.el` so it would emit errors that weren't valid.
Try to load the required package and only show an error if a package fails to load.
I created a separate set of instructions for testing this [here](https://github.com/org-noter/org-noter-with-emacs-basic-test).
Previously org-noter would complain about pdf-tools, nov and djvu with the basic installed as described in testing you now get the following:
```
ATTENTION: org-noter-nov needs the package ‘nov’.
ATTENTION: org-noter-djvu needs the package ‘djvu’.
```
> [ISSUE-9] Try to load packages before emitting a warning that a package is missing.

- org-noter.el
- tests/Notes.org
With this change, if the notes file for a document (tested for PDFs only) has a saved location in the top-level org entry, then upon starting the noter session, the document display is moved to that page.
Previously, this only worked when the session was started from the notes file.
Other minor changes:
1. `t` is not documented as a value for the optional 4th argument of `re-search-forward`.  Implicitly, it is acting as a `1`, but in the documentation `nil` (the default) makes the 4th argument (# of searches forward) `1`.  So the `t` is not needed.
2. Moby Dick in the "tests" subdir has as it's last saved location, page 171, the earlier of the two "Knights and Squires" chapters.
> bugfix: issue #12 (open document to saved location)

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE.md
Hey @petermao, I'd like to add some structure to issues and PR templates. Github has this functionality via the PR templates. I borrowed org-roams for bug reports, you can test drive it here: https://github.com/org-roam/org-roam/issues/new/choose
For PRs, I kinda winged it. The goal is to have some structure around these things.
> Add issue template and PR template.

- .github/workflows/build-test.yml
- Cask
- README.org
- org-noter-test-utils.el
- tests/org-noter-core-tests.el
- tests/org-noter-extra-tests.el
- tests/org-noter-pdf-tests.el
Improve code quality by including a code coverage badge.
Use undercover to generate code coverage and then coveralls.io to visualize this.
This is strictly an on-commit github workflow and doesn't affect org-noter  itself.
See the github workflow succeed.
If you go to https://github.com/org-noter/org-noter/tree/feature/add-test-coverage you should see the badge. It's showing coverage for `master` branch and it won't show up until we merge this to master.
> Add test coverage to builds.

- modules/org-noter-pdf.el
- tests/org-noter-pdf-tests.el
First attempt to deal with Issue #41.
Thus far, this takes keybindings that would not normally be used in pdf-view-mode buffer when running org-noter and runs those keybindings in the notes buffer as if focus was there all along.
`C-c C-c` is used by org-babel to run code.  If user has focus on the document, then it would normally run `doc-view-toggle-display`, which takes the doc buffer out of org-noter-doc-mode.
`C-c C-x C-v` is used by org-babel to toggle inline images.  If user has focus on the document, then `C-c C-x` would normally run `image-toggle-hex-display`, which takes the doc buffer out of org-noter-doc-mode.
I use two keybindings above frequently when running org-babel and generating figures while using `org-noter`, but often enough, I accidentally hit them with focus on the …
> override annoying pdf-view-mode and doc-view-mode keybindings

- org-noter-core.el
- org-noter.el
With `entitiespretty`, underscores in titles look terrible, but org's emphasis decorations make them readable again with minimal disturbance.
Purely cosmetic issue when using `entitespretty` with underscores in the filenames.
New custom variable `org-noter-headline-title-decoration`, default `""`.   Customize to `/` (italics),  `_` (underline), or any other Org emphasis marker (`=`, `~`, `+`).
1. open a pdf and start org noter document
2. customize `org-noter-headline-title-decoration`
3. new headline (document) titles are prepended and appended with the decoration, hiding the formatting from `entitespretty`
> add optional decoration to headline title

- other/org-noter-integration.el
In the series of commits of this PR, I have manually merged our local `org-noter-integration.el` with [org-pdftools/org-noter-pdftools.el](https://github.com/fuxialexander/org-pdftools/blob/4e420233a153a9c4ab3d1a7e1d7d3211c836f0ac/org-noter-pdftools.el), so that the functionality and history of the code can be followed.
The local code may not work out-of-the-box.  The intent here is just to document the changes to that file from the other repository in case we want to later fold in some of the functionality.
In the current `org-noter-pdftools.el`, links use an abbreviated full path (ie, they use `~/`) rather than a relative path to the document.  I think it's better to use relative paths in `org-noter` as that allows sharing of notes/documents over git or cloud services (sycthing, …
> other/org-noter-integration.el == org-pdftools/org-noter-pdftools.el

- README.org
Emacs 29.1 ships use-package. Give example of using it.
Emacs 29.1 ships `use-package` by default. Offer an example how to use it with `org-noter`. 
I added and example to `README.org`.
Add 
```
(use-package org-noter
:load-path "<path-to-org-noter>"
:ensure t
:demand t
)
```
to your `~/.emacs.d/init.el`
> README.org: add installation instructions with Emacs 29.1

- org-noter.el
Some distributions, such as Nixpkgs, use
`normal-top-level-add-subdirs-to-load-path' to recursively add sub dirs of load-path entries to load-path.
org-note also does this when it is loaded using `add-to-list'. Ideally, this should be a no-op since `add-to-list' does deduplication.  However, the entry org-noter adds has a trailing "/", which is not the case for other entries of `load-path'[1].  As a result, the deduplication fails.
[1]: See the source code of `normal-top-level-add-to-load-path'.
Duplicate entry in load-path: /prefix/share/emacs/site-lisp/elpa/org-noter-20230728.2037/modules/
Remove the trailing "/" when adding that path to load-path.
> Remove trailing "/" when expand load-path

- org-noter-core.el
See Issue #61.
The offending command is `org-noter--doc-file-property` which should only run if the `current-buffer` is and Org-mode-derived buffer.  The change skips the body of the code unless the buffer is and Org buffer.
Check against Org 9.6.8 and Org 9.7pre (any commit after f1359546a)
Using `speed-test` and Org 9.6.8, I clocked Moby Dick at 15.07 and 13.29 s, which is significantly faster than using the commit before this one.
> in `--doc-file-property`, ensure buffer is org-mode or pass

- Cask
- modules/org-noter-org-roam.el
- modules/org-noter-pdf.el
- org-noter.el
- tests/org-noter-org-roam-tests.el
org-noter is very opinionated about where notes are to be stored.  This makes using org-roam a bit of a challenge with org-noter. org-roam favours many small notes files over the combined file that org-noter prefers. 
See #2 as well.
In #32, I introduced a hook that allows the file opening process to be overriden. By default, the hook is set to `org-noter--create-session-from-document-file-default` which implements the standard org-noter opening process (mostly `Notes.org` file).
In this PR, I add `org-noter-org-roam` module. This module has `org-noter--create-session-from-document-file-supporting-org-roam` which supports the alternative org-roam workflow.
This functionality has to be enabled by the user by setting the file opening hook like so:
```elisp
(setq …
```
> org-roam integration

- README.org
This updates the PDF-tools URL in the README file. The project at [the old URL](https://github.com/politza/pdf-tools) has been archived and its README now points to [the new URL](https://github.com/vedang/pdf-tools).
> Update PDF-tools URL; old project archived

- org-noter-core.el
The code coverage tool that we're using, undercover, did not work correctly to report code coverag. This is problem #34.
I originally though that edebug needed hints to be included for the macros we use. It turns out that there are hints, and they are incorrect. Removing the hints makes code coverage work better.
See the "Checks" on this PR. Code coverage went from ~4% to 28% because edebug can now correctly analyze the code.
> Remove edebug defs.

- org-noter-test-utils.el
- tests/org-noter-core-tests.el
- tests/org-noter-extra-tests.el
- tests/org-noter-location-tests.el
- tests/org-noter-org-roam-tests.el
- tests/org-noter-pdf-tests.el
Buttercup is failing to run (see #85).
Had to enable lexical binding. But then quoted lambas started failing, so I had to refactor that a bit. 
Run 
cask exec buttercup -L .
> Fix buttercup

- org-noter-core.el
resolve a few compile warnings
* long docstring
* use `forward-line` instead of `next-line`
* \-escape "unescaped single quotes" in docstring
Fixed those things.  Only code change is in `org-noter--update-notes-rename-in-notes`, which is activated via `org-noter-enable-sync-renames`.
- [ X ] I checked the code to make sure that it works on my machine.
1. start org-noter
2. M-x org-noter-enable-sync-renames
3. move a notes file and verify that the paths to linked documents update.
> Fix compile warnings

- docs/customization-recipes.org
This is a documentation only PR. 
It documents 2 "recipes":
1. How to override standard opening process (so that notes can land in arbitrary files, not just `notes.org`). This was implemented as part of org-roam support in #39.
2. Preserving highlights content inside the heading. This is an advice (thanks @petermao !)
> (docs) Add customization recipes 

- modules/org-noter-org-roam.el
See #92.
Catch the error while trying to load org-roam.
> [Issue-92] feat: catch errors on trying to load org-roam to make it truly optional

- Makefile
- org-noter.el
Resolving the bug shared here: https://github.com/org-noter/org-noter/pull/93#issuecomment-2354033667
`version-to-list` only expects digits in the version, but we include the `v`.
Remove the `v` from version.
1. `make bump-patch`
2. Look at org-noter.el and verify that the `Version` field is correct.
> Semver part2
